version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb+srv://kiarajade:PpZ1hZ4n6bqF0Itm@imy220.rfpry.mongodb.net/PlaylistDB?retryWrites=true&w=majority&appName=IMY220
      - JWT_SECRET=$3cur3K3y
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
